### ISSUE TITLE
Deciding on the URL for the client/servers

### ISSUE THREAD

**Issue by mathieuLU** [Lund-University-Biodiversity-data/datahost-api#19]
Which url to chose for both the servers and clients

No requirement for the client I guess. The best would be to have a redirection set up on the https://www.naturdatavardskap.lu.se/ website.
Maybe something like : https://www.naturdatavardskap.lu.se/data that is redirecting to our client instance.

For the server : 
My only requirement would be to have a version number in the url. To make sure we can increment this api version, in case of a major change one day. That won't break some user codes. 
And to stay inline with the best practices regarding the "webhooks"

**Comment by anneliejonsson** [comment]
Ah!

But sure! What you've suggested looks nice and sensible. Let's go with that :-)

**Comment by mathieuLU** [comment]
i also contacted the LU helpdesk. The deal with the network part annd I can't create aliases.
But that would be even better to have : 

for canmove-app.ekol.lu.se:8089/  => http://datahost-client.ekol.lu.se/
for canmove-app.ekol.lu.se:8088/v1/docs  => http://datahost-server.ekol.lu.se/

**Comment by anneliejonsson** [comment]
I'm starting to realise I actually don't understand how aliases work...

I'll draw up an example (focusing on the client) to try and make me understand:
We have the page on our datahost website where I want to place one link that takes the user to the client page.
The page where the links will be placed has the url "https://www.naturdatavardskap.lu.se/tillgang-till-data".
The real url to the client is "canmove-app.ekol.lu.se:8089"
To create the link, without any aliases, I would write something like "Click here to go to the client" on the webpage, and I would type in the real url to the client in Drupal. When the user clicks the llink they will end up on the client page and in the address field they will see the real url.

IF we add an alias, where does it come into the picture?

**Comment by mathieuLU** [comment]
instead of canmove-app.ekol.lu.se:8089, you would write the alias that i would like to create with the help of the helpdesk.
Like :  http://datahost-client.ekol.lu.se/

**Comment by anneliejonsson** [comment]
Ok. And that is also what would be shown up in the address field when I'm on the client page? So one would never actually see the real url? Is that how it works?
If so I'll get on to Inger or the helpdesk. But the alias will have to start with the datahost website name and have an ending that is easy to understand for the user. So I would suggest:

For the client: www.naturdatavardskap.lu.se/tillgang-till-data/sok-data
For the API server/docs: www.naturdatavardskap.lu.se/tillgang-till-data/API-public

**Comment by mathieuLU** [comment]
no it can't be an alias like that with that domain name.

will be easier on zoom. Call me when you have time ;-)

**Comment by anneliejonsson** [comment]
I'm trying to understand this but got confused again when reading through the emails about this . You've actually suggested something very similar to what I first suggested today:
![image](https://user-images.githubusercontent.com/66826408/218078539-439f4f3f-03b8-487b-9aac-3b134dfcd1f9.png)

But yeah, let's talk.

**Comment by mathieuLU** [comment]
V1 we have now : 
client => http://biodiv-app.biol.lu.se/naturdatavardskap-sok-data/
apache server of canmove-app, redirecting to the npm app and hide the score (.htaccess). And using the alias biodiv-app instead of canmove-app

server => http://biodiv-app.biol.lu.se:8088/v1/docs/
the same trick with apache/htaccess worked for the API but not for the /docs page... that's why we keep the port number (so far ?)
