### ISSUE TITLE
new property euTaxonID in openapi.yaml

### ISSUE THREAD

**Issue by mathieuLU** [Lund-University-Biodiversity-data/datahost-api#31]
Add new property: euTaxonID, Text, not required, description: Species code for the observed organism according to EU's Birds Directive (Article 12) or Habitats Directive (Article 17).

**Comment by anneliejonsson** [comment]
We've placed this between "taxonID" and "vernacularName" in the model.

**Comment by mathieuLU** [comment]
fixed with https://github.com/Lund-University-Biodiversity-data/datahost-api-client-nodejs/commit/f88eeed8dab8fe82ab6868c0954fb249016b6de1 and https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/e6691010bf7d098c74dcd5a15857b4abe4316be1
