### ISSUE TITLE
API specifications changes

### ISSUE THREAD

**Issue by mathieuLU** [Lund-University-Biodiversity-data/datahost-api#35]
- Martin's suggestions of optimization (metadata for answer + name changes)
  
 - filter on project name/id

**Comment by mathieuLU** [comment]
**Done:**

Filter models
DatasetFilter, EventsFilter, OccurrenceFilter
·         DatasetList property could be named DatasetIds and the type could change from datasetList to be an array of strings.
DatumFilter
    DatumFilterType property could be named DateFilterType.
Result models
Dataset
·         Events property could be named EventIds.
Event
·         NoObservations property data type could be changed to bool. (note: will be implemented as a codelist in the DPS information exchange model, and as an Boolean in the API specification data model)
·         Occurrences property could be named OccurrenceIds.
Occurrence
·         Event property could be named EventId.


**Won't do :** 

·         Datum property could be named Date.
=> date is a protected name ii many language. It creates problem with the automated code from Swagger API.


**To be done :** 

·         ExportMode property is not a filter and could perhaps be moved to be an endpoint request parameter. (note: query parameter)
GeographicsFilter
·         ResponseCoordinateSystem property is not a filter and could perhaps be moved to be an endpoint request parameter. (note: query parameter)

**Comment by mathieuLU** [comment]
**Other thing to do :** 


Paging

Currently all endpoints that supports paging returns an array with records. I think we should return a paging object to get metadata about the paging result. DIGG have recommendations here:[ https://dev.dataportal.se/rest-api-profil/filtrering-paginering-och-sokparametrar](https://dev.dataportal.se/rest-api-profil/filtrering-paginering-och-sokparametrar)

My suggestion is that the result should look something like this:

{

  "skip": 10,

  "take": 20,

  "count": 20,

  "totalCount": 6232,

  "records": [

    {

      "eventID": "eventId1",

      …

    },

    {

      "eventID": "eventId2",

      …

    },

    …

 ]

}

**Comment by mathieuLU** [comment]
do we want the exportMode=csv available for the 3 GET calls as well ?

**Comment by anneliejonsson** [comment]
I'm guessing you'll ask this question at the API-meeting because I don't know.

About filtering on projectID/name... I saw you mentioned that further up. We decided in the API-meeting that we will delay this to future versions of the API. Just making sure you don't work on something you don't have to at the moment :-)

**Comment by mathieuLU** [comment]
thanks
and yes good that you pointed that, i wanted to do it that week !

**Comment by mathieuLU** [comment]
**Done :** 

· ExportMode property is not a filter and could perhaps be moved to be an endpoint request parameter. (note: query parameter)
GeographicsFilter
· ResponseCoordinateSystem property is not a filter and could perhaps be moved to be an endpoint request parameter. (note: query parameter)

with https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/2e2abeef24e5f6cda245c5ee28f659b0b71b05ee

**Comment by mathieuLU** [comment]
the pagination configuration is ok as well
=> https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/327781e09b1e6ce47375050873f546a90c83b18d

in a V2, i will add the 3 missing fields : 

"skip": 10,

"take": 20,

"count": 20,

**Comment by mathieuLU** [comment]
Done !
with https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/eeba9829d9f5634c493eb16f6e53f598b06ba4bb and https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/e80f996cab93b88939dbc4c425cec7a49cbdd4c4
