### ISSUE TITLE
API URL - events/search - retrieve events based on search parameters, POST request

### ISSUE THREAD

**Issue by mathieuLU** [Lund-University-Biodiversity-data/datahost-api#8]

**Comment by mathieuLU** [comment]
https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/a3287d56ca5d659459faef3cff1c57a746dc9ab3

to test it : 
`curl -X POST -H "Content-Type:application/json" http://canmove-dev.ekol.lu.se:8088/events -d '{"taxon":{"ids":[100062, 102933]}}'`

only the taxon filter so far

**Comment by mathieuLU** [comment]
https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/791cf8a6df8ad9a49c621f52f573f77deff7a004

possibility to filter on counties
and on startDate/endDate
to be continued...


curl -X POST -H "Content-Type: application/json" http://canmove-dev.ekol.lu.se:8088/events -d '{"taxon":{"ids":[100062, 102933]}, "area":{"county":["Skåne län", "Jämtlands län"]}, "date":{"startDate":"'$(date +"%Y-%m-%dT%H:%M:%S%z" -d "1996-04-25T00:00:01")'", "endDate":"'$(date +"%Y-%m-%dT%H:%M:%S%z" -d "1997-06-29T23:59:00")'"}}'

**Comment by mathieuLU** [comment]
possibility to filter with coordinates 
https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/79125e5e80e60be1772bcfa64286253978d81648

`curl -X POST -H "Content-Type: application/json" http://canmove-dev.ekol.lu.se:8088/events -d '{"taxon":{"ids":[100062, 102933]}, "area":{"county":["Skåne län", "Jämtlands län"], "area":{"geographicArea":{"featurePBB":{"geometry":{"type":"Point", "coordinates":[58.64510, 11.77963]}}}, "maxDistanceFromGeometries":12000}}, "date":{"startDate":"'$(date +"%Y-%m-%dT%H:%M:%S%z" -d "1995-05-25T00:00:01")'", "endDate":"'$(date +"%Y-%m-%dT%H:%M:%S%z" -d "1997-06-27T23:59:00")'", "dateFilterType":"BetweenStartDateAndEndDate"}}'`

Only with Point
Needed to change the yml file as well to distinguish featurePBB (point or bounding box) and featureLP (Line or Polygon)

Using the geolib library to calculate distance

How to deal with the errors when no maxDistanceFromGeometries for Point ?
How to deal with the coordinate systems as input ?

**Comment by anneliejonsson** [comment]
> 
About search criteria/filer involving dates:
We decided in the DPS-group to change the model and replace the three current date/time fields (eventDate, eventStartTime and eventEndTime) with only two, i.e. the ones listed below:
eventStartDate (DateTime, required, explanation: Date and time for when the survey started (local time).)
eventEndDate (DateTime, required, explanation: Date and time for when the survey ended (local time).)

Hence, both will include time, but if time is not reported in the programme it will have to be set to a default of e.g. 00:00. Does this make sense?

Will you update the data model with all this info, please? @mathieuLU

**Comment by mathieuLU** [comment]
ok => https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/f400d60fbd4e1e6a9ffed0a3aaa084de30cc4a89

eventDate was marked as required. I've set eventStartDate as required as well. Let me know if it's not the case.

**Comment by anneliejonsson** [comment]
You need to remove eventDate completely, along with eventStartTime and eventEndTime, and instead eadd eventStartDate and eventEndDate. 
Both eventStartDate and eventEndDate are required. And both are the format DateTime.
And copy/paste the explanation for each of the two new fields into the yaml file.

**Comment by mathieuLU** [comment]
Thats whhat I did actually (except setting eventEndDate as required).
Maybe you got confussed by the commit link that displays both old lines of the previous lines (red) and new lines (green)

**Comment by anneliejonsson** [comment]
Ah! Ok, that's fine then :-)

**Comment by mathieuLU** [comment]
geographic filter works => https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/57d7d42fac2c1e69f8b9262551419d239c4bae01

so far I have : 
 - point + distanceMax 
 - BoundingBox : 2 coordinates (or more) to draw a line. Transformed to a BBox, then a polygon. Check if a mitt point of a site is included in the polygon
 - Polygon : X coordinates. Check if a mitt point of a site is included in the polygon

WOrks so far only with sites with mitt point coordinates.
How should it work with more complex sites, when a polygon-site is overlapping a polygon-query ? To be determined.

No mention of any cooordinate system as input. Missing element in the datamodel.yml ? @anneliejonsson

**Comment by mathieuLU** [comment]
The coordinate system as input has to be WGS84. Line added in the datamodel 
[datasetIdArray](https://github.com/Lund-University-Biodiversity-data/datahost-api/commit/3c86ff5e8add95f6a0f4d0b2e6b197b99d712774)
